### ISSUE TITLE
Automatically save pasted data to local storage

### ISSUE THREAD

**Issue by xshshahab** [workmdirfan29/FreeComponentsLib#4]
Problem:
Currently, there is no functionality to automatically save data pasted into a specific field or area to local storage. This feature can enhance the user experience by ensuring that pasted content is retained for future use or reference, even if the page is refreshed or closed accidentally.

1. Proposed Solution:

- Add an event listener for the paste event.
- Capture the pasted content using the clipboard API.
- Automatically store the pasted content in local storage with a unique key.
2. Example Use Case:

- User pastes data into a text input or a designated area.
- The application captures this data and stores it in local storage without any additional user interaction.
- On subsequent visits or page reloads, the data can be retrieved from local storage for continuity.
3.Additional Notes:

Ensure proper sanitization of pasted data to prevent security vulnerabilities.
Provide a mechanism to clear or update stored data if required.

**Comment by workmdirfan29** [comment]
Ok , We will work it on this issue.
